global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'your_password'

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-logistics'
  routes:
    - match:
        severity: critical
      receiver: 'team-logistics-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'team-logistics-warnings'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

receivers:
  - name: 'team-logistics'
    slack_configs:
      - channel: '#logistics-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        
  - name: 'team-logistics-critical'
    slack_configs:
      - channel: '#logistics-critical'
        send_resolved: true
        title: '[CRITICAL] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    email_configs:
      - to: 'team-logistics@example.com'
        send_resolved: true
        headers:
          subject: '[CRITICAL] Logistics System Alert'
        html: '{{ template "email.default.html" . }}'
        
  - name: 'team-logistics-warnings'
    slack_configs:
      - channel: '#logistics-warnings'
        send_resolved: true
        title: '[WARNING] {{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}' 