version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  druid:
    image: apache/druid:latest
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    environment:
      DRUID_XMX: 2g
      DRUID_XMS: 2g
    volumes:
      - druid_data:/var/druid/data

  airflow:
    image: apache/airflow:2.1.3
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://retail_user:retail_password@postgres:5432/retail_db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://retail_user:retail_password@postgres:5432/retail_db
      - CLICKHOUSE_URL=clickhouse://clickhouse:9000
      - DRUID_URL=http://druid:8081
    volumes:
      - .:/app
    depends_on:
      - postgres
      - clickhouse
      - druid

  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://api:8000
    volumes:
      - .:/app
    depends_on:
      - api

volumes:
  postgres_data:
  clickhouse_data:
  druid_data: 