spring:
  application:
    name: commercial-bpms
  datasource:
    url: jdbc:postgresql://localhost:5432/commercial_bpms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  webapp:
    application-path: /camunda
  default-serialization-format: application/json
  job-execution:
    retries: 3
  metrics:
    enabled: true
    db-reporter-activate: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.brunoxabreu: DEBUG
    org.camunda: INFO
    org.springframework: INFO 